### ISSUE TITLE
MT76x2 issue after 5 days uptime on v24.10.0

### ISSUE THREAD

**Issue by alcatraz-zz** [openwrt/mt76#970]
Hey fellas

Got a Xiaomi MI-R3G with 5GHz wifi that stopped working after 5 days uptime. It's running the latest stable 24.10.0 version of OpenWRT.

mt76x2e 0000:02:00.0: MCU message 1f

This appeared in the log. Kernel error something.

Restarting/disable/enable 5ghz did not fix it. I had to restart the router to fix it.

Thanks for all your work.

**Comment by Minha-D** [comment]
I don't know if it will work for you but my cudy wr1300 v1 has same prblm but with different logs where the 5ghz devices can't connect to the network after few hours and restarting adapter doesn't fix but needs full router reboot. !st i thought it was wpd issue,
Recently i disovered it was a driver / firmware issue.
removing and reloading driver fixes the prblm without router reboot. currently i'm using a tem fix where when 5ghz has no clients a script unloads and reloads the driver.

**Comment by weiqi-chen** [comment]
Netgear R6220
OpenWrt 24.10.2 r28739-d9340319c6 / LuCI openwrt-24.10 branch 25.168.50434~d6b13f6
6.6.93

I saw this log show up in dmesg. 
```
[110175.766434] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
[110175.777889] mt76x2e 0000:01:00.0: Build: 1
[110175.786322] mt76x2e 0000:01:00.0: Build Time: 201607111443____
[110175.815014] mt76x2e 0000:01:00.0: Firmware running!
[110175.829364] ieee80211 phy1: Hardware restart was requested
```
After this log, 5G Wireless now working. I try to disconnect and reconnect, my iPhone show "Password not correct".

I run this command below can bing back 5G wireless working:

```
# rmmod mt76x2e
# insmod mt76x2e
wifi reload 
```

I am not sure whether `rmmod` and `insmod` are actually required. During initial troubleshooting, I tried `rmmod` and `insmod` first, but the issue persisted. The 5 GHz wireless only recovered after running `wifi reload` and restarting radio1 in the web interface.

**Comment by lvent** [comment]
I have also been dealing with this myself on a Mi4A gigabit ( ever since I upgraded to 24.10.4 from 23.x something)
Changing any setting related 5ghz also breaks it, unloading and loading driver doesnt fix anything. I also see bunch of frequencies in the list that this chipset doesnt support (like DFS frequencies) using anything more than channel 48 also doesnt seem to work. I dont remember if this was the case all along so I am just putting it out there.

In the end I gave up manually setting frequencies, channel, transmit power and country code and left all on driver default and auto. 

I just updated to 24.10.5, i will update if anything changes.

**Comment by blocktrron** [comment]
@weiqi-chen I did run in the same issue and discovered after the hardware reset the queues are never marked as active.

I've sent this patch upstream:
https://patchwork.kernel.org/project/linux-wireless/patch/20251129023904.288484-1-mail@david-bauer.net/

**Comment by weiqi-chen** [comment]
I upgraded the firmware to OpenWrt 24.10.5 r29087-d9c5716d1d, and it seems the problem was solved. 
I'm not sure whether the issue disappeared because I used a configuration closer to the default settings.
I will post an update if needed.

**Comment by blocktrron** [comment]
Did you observe the firmware crashing? The issue itself shall only happen on firmware crash and we've seen a 100% failure rate in this case. 

Admittedly, the cause is somewhat correlated with AP load and can most easily reproduced in busy environments (30+ STAs)

**Comment by blocktrron** [comment]
Did you observe the firmware crashing? The issue itself shall only happen on firmware crash and we've seen a 100% failure rate in this case. 

Admittedly, the cause is somewhat correlated with AP load and can most easily reproduced in busy environments (30+ STAs)

**Comment by lvent** [comment]
One of my devices is still having problems, though behaviour of the crash seems to have changed. AP that is having problems it the one with most traffic so that might be something to go on.

**Comment by weiqi-chen** [comment]
The "Password not correct" error occurred again.  
To recover from this issue, I used the following commands:  

```bash
rmmod mt76x2e
insmod mt76x2e
wifi reload
# Then I clicked the restart button for radio1
```

Below are the relevant logs:  

```
dmesg | grep -E 'mt7603|mt76x2e'
[   25.274446] mt7603e 0000:02:00.0: enabling device (0000 -> 0002)
[   25.286875] mt7603e 0000:02:00.0: ASIC revision: 76030010
[   25.344233] mt7603e 0000:02:00.0: Firmware Version: ap_pcie
[   25.355477] mt7603e 0000:02:00.0: Build Time: 20160107100755
[   25.424077] mt7603e 0000:02:00.0: firmware init done
[   25.669612] mt7603e 0000:02:00.0: registering led 'mt76-phy0'
[   25.810918] mt76x2e 0000:01:00.0: enabling device (0000 -> 0002)
[   25.823293] mt76x2e 0000:01:00.0: ASIC revision: 76120044
[   26.539822] mt76x2e 0000:01:00.0: ROM patch build: 20141115060606a
[   26.575733] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
[   26.586779] mt76x2e 0000:01:00.0: Build: 1
[   26.595008] mt76x2e 0000:01:00.0: Build Time: 201607111443____
[   26.638649] mt76x2e 0000:01:00.0: Firmware running!
[   26.663774] mt76x2e 0000:01:00.0: registering led 'mt76-phy1'
[   43.988155] mt7603e 0000:02:00.0 phy0-ap0: entered allmulticast mode
[   44.001531] mt7603e 0000:02:00.0 phy0-ap0: entered promiscuous mode
[   45.171419] mt76x2e 0000:01:00.0 phy1-ap0: entered allmulticast mode
[   45.184800] mt76x2e 0000:01:00.0 phy1-ap0: entered promiscuous mode
[  256.962640] mt7603e 0000:02:00.0 phy0-ap0: left allmulticast mode
[  256.975002] mt7603e 0000:02:00.0 phy0-ap0: left promiscuous mode
[  257.038385] mt76x2e 0000:01:00.0 phy1-ap0: left allmulticast mode
[  257.050758] mt76x2e 0000:01:00.0 phy1-ap0: left promiscuous mode
[  258.371767] mt7603e 0000:02:00.0 phy0-ap0: entered allmulticast mode
[  258.385284] mt7603e 0000:02:00.0 phy0-ap0: entered promiscuous mode
[  258.477885] mt76x2e 0000:01:00.0 phy1-ap0: entered allmulticast mode
[  258.491475] mt76x2e 0000:01:00.0 phy1-ap0: entered promiscuous mode
[  259.550156] mt7603e 0000:02:00.0 phy0-ap0: left allmulticast mode
[  259.562575] mt7603e 0000:02:00.0 phy0-ap0: left promiscuous mode
[  260.626751] mt76x2e 0000:01:00.0 phy1-ap0: left allmulticast mode
[  260.639080] mt76x2e 0000:01:00.0 phy1-ap0: left promiscuous mode
[  274.357626] mt76x2e 0000:01:00.0 phy1-ap0: entered allmulticast mode
[  274.371449] mt76x2e 0000:01:00.0 phy1-ap0: entered promiscuous mode
[  274.901385] mt7603e 0000:02:00.0 phy0-ap0: entered allmulticast mode
[  274.914951] mt7603e 0000:02:00.0 phy0-ap0: entered promiscuous mode
[  473.731965] mt7603e 0000:02:00.0 phy0-ap0: left allmulticast mode
[  473.744451] mt7603e 0000:02:00.0 phy0-ap0: left promiscuous mode
[  473.802508] mt76x2e 0000:01:00.0 phy1-ap0: left allmulticast mode
[  473.814966] mt76x2e 0000:01:00.0 phy1-ap0: left promiscuous mode
[  474.795412] mt7603e 0000:02:00.0 phy0-ap0: entered allmulticast mode
[  474.810715] mt7603e 0000:02:00.0 phy0-ap0: entered promiscuous mode
[  474.858566] mt76x2e 0000:01:00.0 phy1-ap0: entered allmulticast mode
[  474.881650] mt76x2e 0000:01:00.0 phy1-ap0: entered promiscuous mode
[  475.830467] mt76x2e 0000:01:00.0 phy1-ap0: left allmulticast mode
[  475.843084] mt76x2e 0000:01:00.0 phy1-ap0: left promiscuous mode
[  476.949797] mt7603e 0000:02:00.0 phy0-ap0: left allmulticast mode
[  476.962099] mt7603e 0000:02:00.0 phy0-ap0: left promiscuous mode
[  489.192710] mt76x2e 0000:01:00.0 phy1-ap0: entered allmulticast mode
[  489.206197] mt76x2e 0000:01:00.0 phy1-ap0: entered promiscuous mode
[  489.573925] mt7603e 0000:02:00.0 phy0-ap0: entered allmulticast mode
[  489.587529] mt7603e 0000:02:00.0 phy0-ap0: entered promiscuous mode
[22002.097938] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
[22002.109005] mt76x2e 0000:01:00.0: Build: 1
[22002.117239] mt76x2e 0000:01:00.0: Build Time: 201607111443____
[22002.144527] mt76x2e 0000:01:00.0: Firmware running!
[46502.872691] mt76x2e 0000:01:00.0 phy1-ap0: left allmulticast mode
[46502.885077] mt76x2e 0000:01:00.0 phy1-ap0: left promiscuous mode
[46505.902438] mt76x2e 0000:01:00.0 phy1-ap0: entered allmulticast mode
[46505.915954] mt76x2e 0000:01:00.0 phy1-ap0: entered promiscuous mode

# after rmmod insmod wifi reload and click restart button from web interface,
# new dmesg logs 

[46505.915954] mt76x2e 0000:01:00.0 phy1-ap0: entered promiscuous mode
[46613.078340] mt76x2e 0000:01:00.0 phy1-ap0 (unregistering): left allmulticast mode
[46613.093387] mt76x2e 0000:01:00.0 phy1-ap0 (unregistering): left promiscuous mode
[46621.260215] mt76x2e 0000:01:00.0: ASIC revision: 76120044
[46622.014377] mt76x2e 0000:01:00.0: ROM patch build: 20141115060606a
[46622.029957] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
[46622.041047] mt76x2e 0000:01:00.0: Build: 1
[46622.049319] mt76x2e 0000:01:00.0: Build Time: 201607111443____
[46622.075511] mt76x2e 0000:01:00.0: Firmware running!
[46622.085921] mt76x2e 0000:01:00.0: registering led 'mt76-phy2'
[46673.318419] mt76x2e 0000:01:00.0 phy2-ap0: entered allmulticast mode
[46673.331880] mt76x2e 0000:01:00.0 phy2-ap0: entered promiscuous mode

```

I noticed that this issue arises after I turn on the second router with the same SSID enabled (located on a different floor).

I will disabled the other wireless  to see is this happen again.

**Comment by blocktrron** [comment]
@weiqi-chen please test with the linked patch, the firmware recovery will always end up in stuck tx queues, no matter the radio configuration.

**Comment by weiqi-chen** [comment]
> [@weiqi-chen](https://github.com/weiqi-chen) please test with the linked patch, the firmware recovery will always end up in stuck tx queues, no matter the radio configuration.

I managed to compile OpenWRT (tag: OpenWrt 24.10.5 r29087-d9c5716d1d) from source, then modify the source code in
`./build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-6.6.119/drivers/net/wireless/mediatek/mt76/mt76x02_mmio.c`,
then run `make package/kernel/mt76/compile`,
and finally reinstall these packages:
```
 opkg install --force-reinstall \
>   kmod-mt76-core_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk \
>   kmod-mt76x02-common_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk \
>   kmod-mt76x2-common_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk \
>   kmod-mt76x2_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk
```
Is there any change in the log that indicates my modification was applied? @blocktrron 

There are no problems after reboot. Let me see if the issue happens again in the future.

**Comment by weiqi-chen** [comment]
> > [@weiqi-chen](https://github.com/weiqi-chen) please test with the linked patch, the firmware recovery will always end up in stuck tx queues, no matter the radio configuration.
> 
> I managed to compile OpenWRT (tag: OpenWrt 24.10.5 r29087-d9c5716d1d) from source, then modify the source code in `./build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-6.6.119/drivers/net/wireless/mediatek/mt76/mt76x02_mmio.c`, then run `make package/kernel/mt76/compile`, and finally reinstall these packages:
> 
> ```
>  opkg install --force-reinstall \
> >   kmod-mt76-core_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk \
> >   kmod-mt76x02-common_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk \
> >   kmod-mt76x2-common_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk \
> >   kmod-mt76x2_6.6.119.2025.11.06~eb567bc7-r1_mipsel_24kc.ipk
> ```
> 
> Is there any change in the log that indicates my modification was applied? [@blocktrron](https://github.com/blocktrron)
> 
> There are no problems after reboot. Let me see if the issue happens again in the future.

No good. same issue happened again.

**Comment by lvent** [comment]
@weiqi-chen what is your radio power on 5g? I have a theory.

**Comment by weiqi-chen** [comment]
> [@weiqi-chen](https://github.com/weiqi-chen) what is your radio power on 5g? I have a theory.

MediaTek MT76x2E 802.11ac/n. Of course.
(MediaTek's 5G wireless network cards/drivers are quite problematic.)

**Comment by mitriyf** [comment]
There is a small theory that this is due to overheating of the device or exceeding the peak speed of the driver. I can only get this error if I start using the network to the fullest...(that is, if we let's say we use a Wi-Fi network at a speed of 70 Mbps)

**Comment by lvent** [comment]
Yeah I think this is hardware unstability related. I reduced my 5g radio transmit power from 200mW to 100mW and so far approximately 24 hours in, I havent had to reboot any of my APs which I previously had to reboot every 3-4 hours at most.

This issue was only with my second ap where it resides in on top of a switch (first ap sits on top of a server with lots of fans).
